services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meal_calories
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
    env_file:
      - ./.env
    environment:
      # Ensure the backend uses the local Postgres in this compose
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/meal_calories
      API_HOST: 0.0.0.0
      API_PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:

